language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_trf"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: DIETClassifier
  epochs: 100

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100



